#install packete with distro based conditions using ansible_facts

---
- name: Install packages
  hosts: servers
  become: yes

  vars:
    pkglist:
      - tree
      - zip
      - wget
      - curl
      - git

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ pkglist }}"
      when: ansible_facts["distribution"] == "Ubuntu" #conditions

    - name: Display installed package
      debug:
        msg: "Installed: {{ item }}"
      loop: "{{ pkglist }}"
      when: ansible_facts["distribution"] == "Ubuntu" #condition